version: '3.8'

services:
  redis-dev:
    image: redis:6
    ports:
      - "6379:6379"
    environment:
      REDIS_ARGS: "--requirepass SecureMeDockerVmRedis --user redis_unizap_dev on >SecureMeDockerVmRedis ~* allcommands --user default off nopass nocommands"
      
    deploy:
      resources:
        limits:
          memory: 1G
    restart: unless-stopped  

  elasticsearch-dev:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.0
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=SecureMeDockerVmElastic
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=false      
    ports:
      - "9200:9200"
    deploy:
      resources:
        limits:
          memory: 1G
    restart: unless-stopped

  mongodb-dev:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo_unizap_dev
      - MONGO_INITDB_ROOT_PASSWORD=SecureMeDockerVmMongo
    ports:
      - "27017:27017"
    deploy:
      resources:
        limits:
          memory: 1G
    restart: unless-stopped

  kafka-dev:
    image: confluentinc/cp-kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper-dev:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://[REPLACE_WITH_EXTERNAL_IP]:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    depends_on:
      - zookeeper-dev
    deploy:
      resources:
        limits:
          memory: 1G
    restart: unless-stopped

  zookeeper-dev:
    image: confluentinc/cp-zookeeper
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
    deploy:
      resources:
        limits:
          memory: 1G
    restart: unless-stopped